name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install GoReleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Run GoReleaser via Makefile
        run: make goreleaser-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}